[package]
name = "cym-modules"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cym-model = { path = "../cym-model" }
cym-ports = { path = "../cym-ports" }
cym-adapters = { path = "../cym-adapters" }
cym-services = { path = "../cym-services" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rayon = "1"
plist = "1"
uuid = "1"
